---
version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
  - package-ecosystem: gomod
    directory: /entrypoint
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
