---
version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    reviewers:
      - asenci
      - NoodlesNZ
  - package-ecosystem: gomod
    directory: /entrypoint
    schedule:
      interval: daily
    reviewers:
      - asenci
      - NoodlesNZ

