---
name: CI

'on':
  push:
  workflow_dispatch:

concurrency:
  group: CI-CD/${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  EARTHLY_CI: 'true'
  FORCE_COLOR: 1

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Earthly
        uses: drugscom/setup-earthly-action@v1
      - name: Run CI tests
        run: earthly +test
      - name: Get Docker image tags
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
      - name: Get docker args
        id: docker
        run: echo "::set-output name=args::--IMAGE_NAME='${{ join(fromJSON(steps.metadata.outputs.json).tags, ' ') }}'"
      - name: Build container image
        run: earthly +docker ${{ steps.docker.outputs.args }}
      - name: Log into registry
        if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: earthly --push +docker ${{ steps.docker.outputs.args }}
